"""
One-Click Bootstrap — Sets up the entire governance foundation.

Run this once to create:
- Unity Catalog catalogs + schemas (per environment)
- Governance tables (audit log, DQ metrics, migration tracking)
- MNPI column masks + row filters
- Monitoring views
- Migration tracking tables (for wave dashboard)

Usage in notebook:
    from aws2lakehouse.bootstrap import Bootstrap
    bootstrap = Bootstrap(org="acme", domains=["risk", "lending", "compliance"])
    sql_output = bootstrap.generate_all()
    # Copy to SQL worksheet and execute, or use spark.sql() per statement
"""


class Bootstrap:
    """
    One-click foundation setup for the entire Lakehouse platform.

    Generates all SQL needed to bootstrap:
    1. Catalog structure (dev/staging/prod per domain)
    2. Common schemas (governance, monitoring, migration_tracking)
    3. Audit logging tables
    4. DQ metrics tables
    5. Migration tracking tables (wave dashboard)
    6. Monitoring views
    7. Grant templates
    """

    def __init__(self, org: str,
                 domains: list[str] = None,
                 environments: list[str] = None,
                 admin_group: str = "data_platform_admins"):
        self.org = org
        self.domains = domains or ["risk", "lending", "compliance", "customer", "analytics"]
        self.environments = environments or ["dev", "staging", "production"]
        self.admin_group = admin_group

    def generate_all(self) -> str:
        """Generate complete bootstrap SQL."""
        sections = [
            self._header(),
            self._catalogs(),
            self._domain_schemas(),
            self._governance_schema(),
            self._monitoring_schema(),
            self._migration_tracking(),
            self._audit_tables(),
            self._dq_tables(),
            self._grants(),
            self._footer(),
        ]
        return "\n\n".join(sections)

    def _header(self) -> str:
        return f"""-- ╔══════════════════════════════════════════════════════════════╗
-- ║  ONE-CLICK BOOTSTRAP: {self.org.upper()} LAKEHOUSE PLATFORM           ║
-- ║  Generated by aws2lakehouse                                 ║
-- ║  Run this in a SQL Warehouse with admin privileges          ║
-- ╚══════════════════════════════════════════════════════════════╝
--
-- This script creates the entire governance foundation:
--   • {len(self.environments)} catalogs (per environment)
--   • {len(self.domains)} domain schemas (per catalog)
--   • Bronze/Silver/Gold layers per domain
--   • Governance, monitoring, and tracking infrastructure
--
-- Prerequisites:
--   • Unity Catalog metastore configured
--   • User has CREATE CATALOG privilege
--   • Admin group '{self.admin_group}' exists in identity provider
"""

    def _catalogs(self) -> str:
        lines = ["-- ═══ STEP 1: CREATE CATALOGS ═══"]
        for env in self.environments:
            cat = f"{self.org}_{env}" if env != "production" else self.org
            lines.append(f"""
CREATE CATALOG IF NOT EXISTS {cat}
COMMENT '{self.org} {env} environment';""")
        return "\n".join(lines)

    def _domain_schemas(self) -> str:
        lines = ["-- ═══ STEP 2: CREATE DOMAIN SCHEMAS (Bronze/Silver/Gold) ═══"]
        for env in self.environments:
            cat = f"{self.org}_{env}" if env != "production" else self.org
            lines.append(f"\nUSE CATALOG {cat};")
            for domain in self.domains:
                for layer in ["bronze", "silver", "gold"]:
                    schema = f"{domain}_{layer}"
                    lines.append(
                        f"CREATE SCHEMA IF NOT EXISTS {schema} "
                        f"COMMENT '{domain} {layer} layer ({env})';")
        return "\n".join(lines)

    def _governance_schema(self) -> str:
        lines = ["-- ═══ STEP 3: GOVERNANCE SCHEMA ═══"]
        for env in self.environments:
            cat = f"{self.org}_{env}" if env != "production" else self.org
            lines.append(f"""
USE CATALOG {cat};
CREATE SCHEMA IF NOT EXISTS governance
COMMENT 'Governance: audit logs, access controls, compliance';""")
        return "\n".join(lines)

    def _monitoring_schema(self) -> str:
        prod_cat = self.org
        return f"""-- ═══ STEP 4: MONITORING SCHEMA ═══
USE CATALOG {prod_cat};

CREATE SCHEMA IF NOT EXISTS monitoring
COMMENT 'Operational monitoring: freshness, volume, DQ metrics, SLA';

CREATE SCHEMA IF NOT EXISTS migration_tracking
COMMENT 'Migration project tracking: inventory, waves, progress';"""

    def _migration_tracking(self) -> str:
        prod_cat = self.org
        return f"""-- ═══ STEP 5: MIGRATION TRACKING TABLES ═══
USE CATALOG {prod_cat};
USE SCHEMA migration_tracking;

-- Pipeline Inventory
CREATE TABLE IF NOT EXISTS pipeline_inventory (
  pipeline_id STRING NOT NULL,
  pipeline_name STRING NOT NULL,
  domain STRING,
  pipeline_type STRING,
  source_system STRING,
  target_layer STRING,
  complexity_score DECIMAL(5,1),
  complexity_category STRING,
  latency_class STRING,
  business_impact STRING,
  mnpi_classification STRING,
  sla_minutes INT,
  estimated_hours DECIMAL(5,1),
  recommended_approach STRING,
  owner STRING,
  dependencies ARRAY<STRING>,
  wave_number INT,
  migration_status STRING DEFAULT 'not_started',
  notes STRING,
  _created_at TIMESTAMP DEFAULT current_timestamp(),
  _updated_at TIMESTAMP
) USING DELTA
COMMENT 'All pipelines discovered during assessment phase'
TBLPROPERTIES ('quality' = 'managed');

-- Wave Configuration
CREATE TABLE IF NOT EXISTS wave_config (
  wave_number INT NOT NULL,
  wave_name STRING,
  start_date DATE,
  target_end_date DATE,
  actual_end_date DATE,
  status STRING DEFAULT 'planned',
  pipeline_count INT,
  total_effort_hours DECIMAL(8,1),
  risk_level STRING,
  notes STRING
) USING DELTA
COMMENT 'Migration wave definitions and scheduling';

-- Daily Progress
CREATE TABLE IF NOT EXISTS migration_progress (
  log_date DATE NOT NULL,
  wave_number INT,
  pipelines_not_started INT,
  pipelines_in_progress INT,
  pipelines_validating INT,
  pipelines_complete INT,
  pipelines_blocked INT,
  effort_remaining_hours DECIMAL(8,1),
  blockers STRING,
  _recorded_at TIMESTAMP DEFAULT current_timestamp()
) USING DELTA
PARTITIONED BY (log_date)
COMMENT 'Daily migration progress snapshots';"""

    def _audit_tables(self) -> str:
        prod_cat = self.org
        return f"""-- ═══ STEP 6: AUDIT & GOVERNANCE TABLES ═══
USE CATALOG {prod_cat};
USE SCHEMA governance;

-- Audit Log (7-year retention)
CREATE TABLE IF NOT EXISTS audit_log (
  event_id STRING DEFAULT uuid(),
  event_timestamp TIMESTAMP DEFAULT current_timestamp(),
  event_type STRING,           -- access, modify, export, query
  principal STRING,            -- user or service principal
  action STRING,               -- SELECT, INSERT, UPDATE, DELETE, GRANT
  resource_type STRING,        -- table, view, volume, function
  resource_name STRING,        -- fully qualified name
  details MAP<STRING, STRING>, -- additional context
  source_ip STRING,
  session_id STRING
) USING DELTA
PARTITIONED BY (date_trunc('month', event_timestamp))
COMMENT 'Compliance audit log - 7 year retention'
TBLPROPERTIES (
  'delta.logRetentionDuration' = 'interval 2555 days',
  'delta.deletedFileRetentionDuration' = 'interval 2555 days'
);

-- MNPI Access Registry
CREATE TABLE IF NOT EXISTS mnpi_registry (
  table_name STRING NOT NULL,
  column_name STRING,
  classification STRING,       -- mnpi, pii, confidential
  mask_function STRING,        -- function used for masking
  authorized_groups ARRAY<STRING>,
  embargo_hours INT DEFAULT 0,
  registered_at TIMESTAMP DEFAULT current_timestamp(),
  registered_by STRING
) USING DELTA
COMMENT 'Registry of all MNPI/PII columns and their access controls';"""

    def _dq_tables(self) -> str:
        prod_cat = self.org
        return f"""-- ═══ STEP 7: DATA QUALITY METRICS TABLES ═══
USE CATALOG {prod_cat};
USE SCHEMA monitoring;

-- Freshness Metrics
CREATE TABLE IF NOT EXISTS freshness_metrics (
  table_name STRING NOT NULL,
  check_timestamp TIMESTAMP DEFAULT current_timestamp(),
  last_updated TIMESTAMP,
  staleness_minutes DECIMAL(10,1),
  sla_minutes INT,
  sla_status STRING,           -- OK, WARNING, BREACH
  owner STRING
) USING DELTA
PARTITIONED BY (date_trunc('day', check_timestamp))
COMMENT 'Table freshness monitoring metrics';

-- Volume Metrics
CREATE TABLE IF NOT EXISTS volume_metrics (
  table_name STRING NOT NULL,
  check_date DATE DEFAULT current_date(),
  row_count BIGINT,
  size_bytes BIGINT,
  rolling_avg_rows DECIMAL(15,1),
  deviation_pct DECIMAL(5,2),
  anomaly_status STRING        -- normal, low, high
) USING DELTA
PARTITIONED BY (check_date)
COMMENT 'Table volume monitoring (anomaly detection)';

-- DQ Scores
CREATE TABLE IF NOT EXISTS dq_scores (
  table_name STRING NOT NULL,
  check_timestamp TIMESTAMP DEFAULT current_timestamp(),
  rule_name STRING,
  total_rows BIGINT,
  passing_rows BIGINT,
  pass_rate DECIMAL(5,4),
  threshold DECIMAL(5,4),
  status STRING               -- PASS, FAIL, WARN
) USING DELTA
COMMENT 'Data quality rule execution results';

-- Pipeline Run History
CREATE TABLE IF NOT EXISTS pipeline_runs (
  pipeline_name STRING NOT NULL,
  run_id STRING,
  run_start TIMESTAMP,
  run_end TIMESTAMP,
  duration_seconds INT,
  status STRING,              -- SUCCESS, FAILED, TIMEOUT
  rows_processed BIGINT,
  error_message STRING
) USING DELTA
PARTITIONED BY (date_trunc('day', run_start))
COMMENT 'Pipeline execution history for SLA tracking';"""

    def _grants(self) -> str:
        prod_cat = self.org
        lines = ["-- ═══ STEP 8: GRANTS ═══"]
        for env in self.environments:
            cat = f"{self.org}_{env}" if env != "production" else self.org
            lines.append(f"""
-- Admin group gets full access
GRANT ALL PRIVILEGES ON CATALOG {cat} TO `{self.admin_group}`;
GRANT USE CATALOG ON CATALOG {cat} TO `{self.admin_group}`;""")

        lines.append(f"""
-- Domain-specific grants (customize per team)
-- Example: Risk team gets their schemas
-- GRANT USE SCHEMA, SELECT ON SCHEMA {prod_cat}.risk_bronze TO `risk_team`;
-- GRANT USE SCHEMA, SELECT ON SCHEMA {prod_cat}.risk_silver TO `risk_team`;
-- GRANT USE SCHEMA, SELECT ON SCHEMA {prod_cat}.risk_gold TO `risk_team`;

-- Read-only for monitoring
-- GRANT USE SCHEMA, SELECT ON SCHEMA {prod_cat}.monitoring TO `all_engineers`;
-- GRANT USE SCHEMA, SELECT ON SCHEMA {prod_cat}.migration_tracking TO `all_engineers`;""")
        return "\n".join(lines)

    def _footer(self) -> str:
        return f"""-- ═══ BOOTSTRAP COMPLETE ═══
--
-- Next steps:
--   1. Run discovery:  from aws2lakehouse.discovery import PipelineInventory
--   2. Populate inventory: INSERT INTO migration_tracking.pipeline_inventory ...
--   3. Plan waves: from aws2lakehouse.discovery import WavePlanner
--   4. Start pilot: See docs/QUICKSTART.md
--
-- Generated for: {self.org}
-- Environments: {', '.join(self.environments)}
-- Domains: {', '.join(self.domains)}
"""

    def generate_notebook(self) -> str:
        """Generate as a Databricks notebook (with %sql magic)."""
        sql = self.generate_all()
        cells = sql.split("-- ═══ STEP")

        notebook = "# Databricks notebook source\n"
        notebook += "# MAGIC %md\n"
        notebook += f"# MAGIC # One-Click Bootstrap: {self.org}\n"
        notebook += "# MAGIC Run all cells to set up the complete Lakehouse governance foundation.\n\n"

        for cell in cells:
            if cell.strip():
                notebook += "# COMMAND ----------\n\n"
                notebook += "# MAGIC %sql\n"
                for line in cell.strip().split("\n"):
                    notebook += f"# MAGIC {line}\n"
                notebook += "\n"

        return notebook
