"""
docs_generator.py — Auto-generates project-specific documentation during migration.

When migrate.py runs, this module produces a docs/ folder in the output repo
containing documentation TAILORED to the actual pipelines migrated — not generic templates.

Output:
  dest_repo/
  └── docs/
      ├── README.md                          (project overview + deploy guide)
      ├── MIGRATION_REPORT.md                (what was migrated, from where, stats)
      ├── ARCHITECTURE.md                    (target architecture for THIS project)
      ├── GOVERNANCE.md                      (MNPI/PII controls applied)
      ├── INGESTION_PATTERNS.md              (patterns used in THIS migration)
      ├── RUNBOOK.md                         (how to operate these specific pipelines)
      ├── VALIDATION_CHECKLIST.md            (pre/post cutover steps)
      └── WAVE_PLAN.md                       (migration wave assignments)
"""
import re
from datetime import datetime
from pathlib import Path
from typing import Any

_NL = "\n"


def _wave_row(p: dict) -> str:
    """Format a single pipeline row for the wave plan table."""
    effort = "4h" if p.get("source_type") in ("auto_loader", "delta_table") else "1-2d"
    impact = p.get("business_impact", "medium")
    return f"| {p['name']} | {p['domain']} | {p['source_type']} | {impact} | {effort} |\n"


class DocsGenerator:
    """Generates migration-specific documentation from actual pipeline artifacts."""

    def __init__(self, project_name: str, org: str, catalog: str,
                 inventory: list[dict], artifacts: list[Any],
                 source_path: str, dest_path: str):
        self.project_name = project_name
        self.org = org
        self.catalog = catalog
        self.inventory = inventory
        self.artifacts = artifacts
        self.source_path = source_path
        self.dest_path = dest_path
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        self.domains = sorted(set(p["domain"] for p in inventory))
        self.source_types = sorted(set(p["source_type"] for p in inventory))

    def _sla_range(self) -> str:
        """Return 'min-max' SLA range string from inventory."""
        sla_min = min((p.get("sla_minutes", 60) for p in self.inventory), default=60)
        sla_max = max((p.get("sla_minutes", 240) for p in self.inventory), default=240)
        return f"{sla_min}-{sla_max}"

    @staticmethod
    def _frequency_bucket(schedule: str) -> str:
        """D3: Classify schedule into frequency bucket by parsing cron."""
        if not schedule:
            return "daily"
        if schedule == "continuous":
            return "streaming"
        if schedule == "triggered":
            return "triggered"
        # Match */N minute patterns
        m = re.match(r"\*/?(\d+)\s", schedule)
        if m:
            minutes = int(m.group(1))
            if minutes <= 5:
                return "streaming"
            elif minutes <= 60:
                return "high_frequency"
        # Hourly: "0 * * * *" or "0 */N * * *"
        if re.match(r"0\s+\*", schedule) or re.match(r"0\s+\*/\d", schedule):
            return "high_frequency"
        # Default daily or less frequent
        return "daily"

    def generate_all(self):
        """Generate all documentation files."""
        docs_path = f"{self.dest_path}/docs"
        Path(docs_path).mkdir(parents=True, exist_ok=True)

        self._write(docs_path, "MIGRATION_REPORT.md", self._migration_report())
        self._write(docs_path, "ARCHITECTURE.md", self._architecture())
        self._write(docs_path, "GOVERNANCE.md", self._governance())
        self._write(docs_path, "INGESTION_PATTERNS.md", self._ingestion_patterns())
        self._write(docs_path, "RUNBOOK.md", self._runbook())
        self._write(docs_path, "VALIDATION_CHECKLIST.md", self._validation_checklist())
        self._write(docs_path, "WAVE_PLAN.md", self._wave_plan())

        return 7  # number of docs generated

    def _write(self, path, filename, content):
        Path(f"{path}/{filename}").write_text(content, encoding="utf-8")

    # ─── MIGRATION REPORT ──────────────────────────────────────────────────────
    def _migration_report(self):
        pipeline_table = "\n".join(
            f"| {p['name']} | {p['domain']} | {p['source_type']} | "
            f"{p.get('schedule','N/A')} | {p.get('classification','internal')} | "
            f"{p.get('business_impact','medium')} |"
            for p in self.inventory
        )

        mnpi_pipelines = [p for p in self.inventory if p.get("classification") == "mnpi"]
        pii_pipelines = [p for p in self.inventory if p.get("pii_columns")]
        critical_pipelines = [p for p in self.inventory if p.get("business_impact") == "critical"]

        return f"""# Migration Report

> Auto-generated by aws2lakehouse on {self.timestamp}

## Summary

| Metric | Value |
|--------|-------|
| Source project | `{self.source_path}` |
| Target project | `{self.dest_path}` |
| Pipelines migrated | {len(self.inventory)} |
| Domains | {len(self.domains)} ({", ".join(self.domains)}) |
| Source types | {len(self.source_types)} ({", ".join(self.source_types)}) |
| Artifacts generated | {len(self.artifacts) * 6} files |
| Target catalog | `{self.catalog}` |
| Organization | {self.org} |

## Risk Profile

| Classification | Count | Pipelines |
|---------------|-------|-----------|
| MNPI | {len(mnpi_pipelines)} | {", ".join(p["name"] for p in mnpi_pipelines) or "None"} |
| PII (Confidential) | {len(pii_pipelines)} | {", ".join(p["name"] for p in pii_pipelines) or "None"} |
| Critical (business impact) | {len(critical_pipelines)} | {", ".join(p["name"] for p in critical_pipelines) or "None"} |
| Internal | {len([p for p in self.inventory if p.get("classification") not in ("mnpi", "confidential") and not p.get("pii_columns")])} | Remaining |

## Pipeline Inventory

| Pipeline | Domain | Source | Schedule | Classification | Impact |
|----------|--------|--------|----------|----------------|--------|
{pipeline_table}

## Artifacts Generated (Per Pipeline)

Each pipeline produces 6 files:

| Artifact | Location | Purpose |
|----------|----------|---------|
| Notebook | `src/pipelines/{{domain}}/bronze/{{name}}.py` | Ingestion code |
| Job YAML | `resources/jobs/{{name}}.yml` | Schedule + compute config |
| DQ SQL | `quality/{{name}}_expectations.sql` | Data quality checks |
| Governance | `governance/column_masks/{{name}}.sql` | Tags + column masks |
| Tests | `tests/validation/test_{{name}}.py` | Migration validation |
| Monitoring | `monitoring/{{name}}_monitoring.sql` | Freshness + volume alerts |

## Deploy

```bash
# Validate
databricks bundle validate --target dev

# Deploy to dev
databricks bundle deploy --target dev

# Deploy to production (requires approval)
databricks bundle deploy --target production
```
"""

    # ─── ARCHITECTURE ──────────────────────────────────────────────────────────
    def _architecture(self):
        schema_list = "\n".join(
            f"  - `{self.catalog}.{d}_bronze`\n  - `{self.catalog}.{d}_silver`\n  - `{self.catalog}.{d}_gold`"
            for d in self.domains
        )

        return f"""# Target Architecture

> Specific to this migration: {len(self.inventory)} pipelines across {len(self.domains)} domains

## Unity Catalog Structure

```
{self.catalog}/                         ← Production catalog
{"".join(f"├── {d}_bronze/              ← Raw ingestion ({d}){_NL}" for d in self.domains)}{"".join(f"├── {d}_silver/              ← Curated ({d}){_NL}" for d in self.domains)}{"".join(f"├── {d}_gold/                ← Serving ({d}){_NL}" for d in self.domains)}├── _governance/              ← Audit, MNPI registry
└── _monitoring/              ← Pipeline metrics, DQ scores
```

## Schemas Created

{schema_list}

## Compute Strategy

| Pipeline Pattern | Compute Type | Pipelines |
|-----------------|-------------|-----------|
| Streaming (continuous) | Always-on cluster | {", ".join(p["name"] for p in self.inventory if self._frequency_bucket(p.get("schedule","")) == "streaming") or "None"} |
| High-frequency (<1hr) | Serverless | {", ".join(p["name"] for p in self.inventory if self._frequency_bucket(p.get("schedule","")) == "high_frequency") or "None"} |
| Daily batch | Job cluster (auto-terminate) | {", ".join(p["name"] for p in self.inventory if self._frequency_bucket(p.get("schedule","")) == "daily") or "None"} |
| Event-triggered | Serverless (file arrival) | {", ".join(p["name"] for p in self.inventory if self._frequency_bucket(p.get("schedule","")) == "triggered") or "None"} |

## Data Flow

```
Sources                    Bronze              Silver              Gold
───────                    ──────              ──────              ────
{"".join(f"{p['source_type']:<25} → {p['domain']}_bronze      → {p['domain']}_silver      → {p['domain']}_gold{_NL}" for p in self.inventory[:6])}```
"""

    # ─── GOVERNANCE ────────────────────────────────────────────────────────────
    def _governance(self):
        mnpi_details = ""
        for p in self.inventory:
            if p.get("mnpi_columns"):
                mnpi_details += f"\n### {p['name']}\n"
                mnpi_details += f"- **Table:** `{self.catalog}.{p['domain']}_bronze.{p['name']}`\n"
                mnpi_details += f"- **MNPI columns:** {', '.join(f'`{c}`' for c in p['mnpi_columns'])}\n"
                mnpi_details += f"- **Mask function:** Only visible to `{p['domain']}_team` group\n"

        pii_details = ""
        for p in self.inventory:
            if p.get("pii_columns"):
                pii_details += f"\n### {p['name']}\n"
                pii_details += f"- **Table:** `{self.catalog}.{p['domain']}_bronze.{p['name']}`\n"
                pii_details += f"- **PII columns:** {', '.join(f'`{c}`' for c in p['pii_columns'])}\n"
                pii_details += "- **Mask:** SHA-256 hash for unauthorized users\n"

        return f"""# Governance Controls

> Applied to {len(self.inventory)} tables in `{self.catalog}` catalog

## Classification Tags

All tables are auto-tagged with:
```sql
ALTER TABLE {{table}} SET TAGS ('data_classification' = '{{classification}}');
ALTER TABLE {{table}} SET TAGS ('domain' = '{{domain}}', 'owner' = '{{owner}}');
```

## MNPI Column Masks
{mnpi_details or "No MNPI columns detected in this migration."}

## PII Column Masks
{pii_details or "No PII columns detected in this migration."}

## Access Control Groups

| Group | Access Level | Tables |
|-------|-------------|--------|
{"".join(f"| `{d}_team` | Full access to `{d}_*` schemas | All {d} tables |{_NL}" for d in self.domains)}| `data_engineering` | All schemas (manage) | All |
| `analysts` | Silver + Gold (read only) | Governed views |
| `compliance` | Full access (audit) | All + audit logs |

## Audit

All access is logged to `{self.catalog}._governance.audit_log` with 7-year retention.
"""

    # ─── INGESTION PATTERNS ────────────────────────────────────────────────────
    def _ingestion_patterns(self):
        patterns_used = {}
        for p in self.inventory:
            st = p["source_type"]
            if st not in patterns_used:
                patterns_used[st] = []
            patterns_used[st].append(p["name"])

        pattern_sections = ""
        for source_type, pipelines in sorted(patterns_used.items()):
            pattern_sections += f"""
### {source_type.replace("_", " ").title()} ({len(pipelines)} pipelines)

**Pipelines:** {", ".join(pipelines)}

**Pattern:** See `src/pipelines/*/bronze/{pipelines[0]}.py` for reference implementation.

"""

        return f"""# Ingestion Patterns Used

> {len(patterns_used)} distinct ingestion patterns across {len(self.inventory)} pipelines

## Pattern Summary

| Source Type | Count | Pipelines |
|-------------|-------|-----------|
{"".join(f"| {st} | {len(ps)} | {', '.join(ps)} |{_NL}" for st, ps in sorted(patterns_used.items()))}

## Pattern Details
{pattern_sections}

## Common Configuration

All pipelines use:
- **Secrets:** `dbutils.secrets.get(scope, key)` — no hardcoded credentials
- **Parameterization:** `os.getenv("CATALOG")`, `os.getenv("SCHEMA")`, `os.getenv("TABLE")`
- **Audit columns:** `_ingested_at` (timestamp), `_source_file` (for file-based)
- **Schema evolution:** `mergeSchema=true` on all writes
- **Checkpointing:** `/Volumes/{{catalog}}/{{schema}}/_checkpoints/{{pipeline}}`
"""

    # ─── RUNBOOK ───────────────────────────────────────────────────────────────
    def _runbook(self):
        # D5: Generate for ALL pipelines, grouped by domain
        pipeline_runbooks = ""
        by_domain = {}
        for p in self.inventory:
            by_domain.setdefault(p.get("domain", "default"), []).append(p)

        for domain in sorted(by_domain.keys()):
            pipeline_runbooks += f"\n## {domain.title()} Domain\n"
            for p in by_domain[domain]:
                pipeline_runbooks += f"""
### {p["name"]}
- **Schedule:** `{p.get("schedule", "N/A")}`
- **SLA:** {p.get("sla_minutes", 60)} minutes
- **Owner:** {p.get("owner", "data-team")}
- **On failure:** Check job run in Workflows UI → Review error in notebook output
- **Rerun:** `databricks jobs run-now --job-id <job_id>`
- **Backfill:** Modify `CATALOG`/`SCHEMA` parameters, run manually
"""

        return f"""# Operations Runbook

> How to operate and troubleshoot the {len(self.inventory)} pipelines in this project

## Quick Reference

| Action | Command |
|--------|---------|
| Deploy | `databricks bundle deploy --target prod` |
| Check status | `databricks jobs list --output JSON | grep {self.org}` |
| View runs | Workspace → Workflows → filter by tag:domain |
| Rerun failed | `databricks jobs run-now --job-id <id>` |
| View logs | Workspace → Job Run → click task → view notebook output |

## Pipeline-Specific Runbooks
{pipeline_runbooks}

## Common Issues & Fixes

| Symptom | Cause | Fix |
|---------|-------|-----|
| "Table not found" | Schema not created | Run `governance/bootstrap.sql` |
| "Permission denied" | Missing grants | Check group membership in UC |
| Stale data (SLA breach) | Upstream delayed | Check dependency pipeline status |
| Volume anomaly (spike) | Source change | Verify with source team, check DQ |
| Streaming lag | Insufficient compute | Scale cluster or increase trigger interval |

## Monitoring Queries

```sql
-- Check pipeline freshness
SELECT pipeline_name,
       TIMESTAMPDIFF(MINUTE, MAX(completed_at), CURRENT_TIMESTAMP()) as minutes_stale
FROM {self.catalog}._monitoring.pipeline_runs
GROUP BY 1 HAVING minutes_stale > 60;

-- Check DQ failures
SELECT * FROM {self.catalog}._monitoring.dq_scores
WHERE score < 0.95 AND check_date = CURRENT_DATE;
```

## Escalation Path

1. **L1 (On-call engineer):** Rerun job, check obvious errors
2. **L2 (Domain engineer):** Investigate data issues, schema changes
3. **L3 (Platform team):** Cluster issues, permission problems, infra
4. **Compliance:** Any MNPI/PII-related alerts
"""

    # ─── VALIDATION CHECKLIST ──────────────────────────────────────────────────
    def _validation_checklist(self):
        pipeline_checks = "\n".join(
            f"- [ ] **{p['name']}**: Row count ✓ | Schema ✓ | Aggregates ✓ | SLA ✓"
            for p in self.inventory
        )

        return f"""# Migration Validation Checklist

> Complete ALL checks before cutting over each pipeline to production

## Pre-Cutover (Per Pipeline)

{pipeline_checks}

## Validation Steps

### 1. Data Parity
```bash
# Run auto-generated validation tests
databricks bundle run validation-tests --target staging
```

Each test in `tests/validation/test_{{pipeline}}.py` checks:
- Row count comparison (AWS vs Databricks)
- Schema match (column names + types)
- Aggregate comparison (SUM, AVG, MIN, MAX)
- Null count comparison
- Sample record hash

### 2. SLA Verification
- [ ] Run pipeline 3 consecutive days
- [ ] All runs complete within SLA ({self._sla_range()} min depending on pipeline)
- [ ] No SLA breaches

### 3. Governance Verification
- [ ] All tables tagged (classification, domain, owner)
- [ ] Column masks applied (test with non-privileged user)
- [ ] Row filters working (test embargo periods if applicable)
- [ ] Audit log capturing access events

### 4. Monitoring Verification
- [ ] Freshness alerts firing correctly
- [ ] Volume anomaly detection working
- [ ] DQ scores being recorded
- [ ] Slack/email notifications delivering

## Post-Cutover (7-Day Hypercare)

- [ ] Day 1-3: Monitor all pipeline runs, compare with AWS
- [ ] Day 4-5: Disable AWS pipeline (keep data for comparison)
- [ ] Day 6-7: Confirm no consumer complaints
- [ ] Day 7: Final sign-off from pipeline owner
- [ ] Decommission AWS resources

## Rollback Plan

If issues found during hypercare:
1. Re-enable AWS pipeline
2. Notify consumers
3. Investigate root cause
4. Fix and re-validate
5. Retry cutover
"""

    # ─── WAVE PLAN ─────────────────────────────────────────────────────────────
    def _wave_plan(self):
        # D4: Sort by complexity ASC before assignment — simple pipelines pilot first
        complexity_order = {"low": 0, "medium": 1, "high": 2, "critical": 3}
        sorted_inventory = sorted(
            self.inventory,
            key=lambda p: (
                complexity_order.get(p.get("business_impact", "medium"), 1),
                0 if p.get("source_type") in ("auto_loader", "delta_table") else 1
            )
        )

        waves = {"Wave 0 (Pilot)": [], "Wave 1": [], "Wave 2": [], "Wave 3": []}
        for i, p in enumerate(sorted_inventory):
            if i < 3 and p.get("business_impact") != "critical":
                waves["Wave 0 (Pilot)"].append(p)
            elif p.get("business_impact") == "critical":
                waves["Wave 1"].append(p)
            elif p.get("source_type") in ("kafka", "jdbc"):
                waves["Wave 2"].append(p)
            else:
                waves["Wave 3"].append(p)

        wave_sections = ""
        for wave_name, pipelines in waves.items():
            if pipelines:
                wave_sections += f"""
### {wave_name} ({len(pipelines)} pipelines)

| Pipeline | Domain | Source | Impact | Est. Effort |
|----------|--------|--------|--------|-------------|
{"".join(_wave_row(p) for p in pipelines)}
"""

        return f"""# Wave Plan

> Migration roadmap for {len(self.inventory)} pipelines across {len(self.domains)} domains

## Timeline Estimate

| Wave | Pipelines | Duration | Milestone |
|------|-----------|----------|-----------|
| Wave 0 (Pilot) | 3 | Week 1-2 | Validate approach |
| Wave 1 (Critical) | {len(waves.get("Wave 1",[]))} | Week 3-4 | High-value pipelines live |
| Wave 2 (Core) | {len(waves.get("Wave 2",[]))} | Week 5-6 | Majority migrated |
| Wave 3 (Remaining) | {len(waves.get("Wave 3",[]))} | Week 7-8 | All pipelines migrated |

## Wave Details
{wave_sections}

## Dependencies

Pipelines are ordered to respect data dependencies:
- Bronze pipelines migrate first (no upstream deps)
- Silver pipelines follow (depend on bronze)
- Gold pipelines last (depend on silver)

## Success Criteria Per Wave

| Wave | Criteria |
|------|----------|
| Pilot | Data parity confirmed, SLA met, governance applied |
| Wave 1 | All critical pipelines live, no SLA regression |
| Wave 2 | All core pipelines live, monitoring active |
| Wave 3 | All pipelines migrated, AWS decommissioned |
"""
