"""
CI/CD Module — Databricks Asset Bundles, deployment pipelines, and IaC standards.

Provides:
- Databricks Asset Bundle (DAB) template generation
- GitHub Actions / Azure DevOps pipeline templates
- Multi-environment deployment configuration
- Branching strategy and quality gates
- Infrastructure-as-Code for clusters, jobs, and permissions
"""

from typing import Dict, List, Optional
from dataclasses import dataclass, field
import json
import logging

logger = logging.getLogger(__name__)


class DABGenerator:
    """
    Generates Databricks Asset Bundle (DAB) configurations.
    
    Creates a complete bundle structure including:
    - databricks.yml (bundle definition)
    - resources/ (jobs, pipelines, schemas)
    - src/ (notebooks, python files)
    - tests/ (integration tests)
    
    Usage:
        generator = DABGenerator(
            project_name="apex-risk-pipeline",
            environments=["dev", "staging", "production"],
            catalog_prefix="apex"
        )
        files = generator.generate()
    """
    
    def __init__(
        self,
        project_name: str,
        environments: List[str] = None,
        catalog_prefix: str = "enterprise",
        default_cluster_policy: str = "shared-autoscaling",
        git_url: str = ""
    ):
        self.project_name = project_name
        self.environments = environments or ["dev", "staging", "production"]
        self.catalog_prefix = catalog_prefix
        self.default_cluster_policy = default_cluster_policy
        self.git_url = git_url
    
    def generate_bundle_yaml(self) -> str:
        """Generate the main databricks.yml configuration."""
        
        targets = ""
        for env in self.environments:
            workspace_host = f"https://{env}.cloud.databricks.com"  # Placeholder
            catalog = f"{self.catalog_prefix}_{env}"
            
            targets += f"""
  {env}:
    mode: {"development" if env == "dev" else "production"}
    default_catalog: {catalog}
    workspace:
      host: {workspace_host}
    variables:
      catalog: {catalog}
      environment: {env}
      warehouse_size: {"SMALL" if env == "dev" else "MEDIUM" if env == "staging" else "LARGE"}
"""
        
        return f"""# Databricks Asset Bundle Configuration
# Project: {self.project_name}
# Generated by aws2lakehouse

bundle:
  name: {self.project_name}
  
variables:
  catalog:
    description: "Unity Catalog name"
    default: "{self.catalog_prefix}_dev"
  environment:
    description: "Deployment environment"
    default: "dev"

include:
  - resources/*.yml

targets:{targets}
"""
    
    def generate_job_resource(self, job_name: str, tasks: List[Dict]) -> str:
        """Generate a job resource YAML."""
        
        task_yaml_parts = []
        for task in tasks:
            task_yaml = f"""
      - task_key: {task['task_key']}
        notebook_task:
          notebook_path: ../src/{task.get('notebook', task['task_key'])}.py
          base_parameters:
            catalog: "${{var.catalog}}"
            environment: "${{var.environment}}"
        job_cluster_key: shared_cluster"""
            
            if task.get('depends_on'):
                deps = "\n".join(f"            - task_key: {d}" for d in task['depends_on'])
                task_yaml += f"""
        depends_on:
{deps}"""
            task_yaml_parts.append(task_yaml)
        
        tasks_yaml = "".join(task_yaml_parts)
        
        return f"""# Job: {job_name}
resources:
  jobs:
    {job_name}:
      name: "${{bundle.name}}-{job_name}-${{var.environment}}"
      tasks:{tasks_yaml}
      
      job_clusters:
        - job_cluster_key: shared_cluster
          new_cluster:
            spark_version: "15.4.x-photon-scala2.12"
            node_type_id: i3.xlarge
            num_workers: 4
            spark_conf:
              spark.sql.adaptive.enabled: "true"
              spark.databricks.delta.optimizeWrite.enabled: "true"
      
      schedule:
        quartz_cron_expression: "0 0 6 * * ?"
        timezone_id: "UTC"
        pause_status: PAUSED
      
      email_notifications:
        on_failure:
          - data-engineering@company.com
      
      tags:
        project: {self.project_name}
        environment: "${{var.environment}}"
        managed_by: databricks_asset_bundle
"""
    
    def generate_github_actions(self) -> str:
        """Generate GitHub Actions CI/CD pipeline."""
        return """# .github/workflows/deploy.yml
# Databricks Asset Bundle CI/CD Pipeline

name: Deploy Databricks Bundle

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

env:
  DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
  DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

jobs:
  validate:
    name: Validate Bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      
      - name: Validate bundle
        run: databricks bundle validate
      
      - name: Run unit tests
        run: |
          pip install pytest
          pytest tests/unit/ -v

  deploy-staging:
    name: Deploy to Staging
    needs: validate
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      
      - name: Deploy to staging
        run: databricks bundle deploy --target staging
      
      - name: Run integration tests
        run: databricks bundle run integration_test_job --target staging

  deploy-production:
    name: Deploy to Production
    needs: validate
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
      
      - name: Deploy to production
        run: databricks bundle deploy --target production
"""
    
    def generate_project_structure(self) -> Dict[str, str]:
        """Generate complete DAB project file structure."""
        return {
            "databricks.yml": self.generate_bundle_yaml(),
            ".github/workflows/deploy.yml": self.generate_github_actions(),
            "resources/README.md": "# Job and pipeline resource definitions\n",
            "src/README.md": "# Source notebooks and Python scripts\n",
            "tests/unit/README.md": "# Unit tests\n",
            "tests/integration/README.md": "# Integration tests (run on Databricks)\n",
        }


class BranchStrategy:
    """
    Git branching strategy for data engineering teams.
    
    Recommended: GitFlow-lite
    - main → production deployments
    - develop → staging (integration)
    - feature/* → development work
    - hotfix/* → production fixes
    - release/* → release candidates
    """
    
    @staticmethod
    def generate_branch_protection_rules() -> Dict:
        """Generate GitHub branch protection configuration."""
        return {
            "main": {
                "required_reviews": 2,
                "dismiss_stale_reviews": True,
                "require_code_owner_reviews": True,
                "required_status_checks": [
                    "validate",
                    "deploy-staging"
                ],
                "enforce_admins": True,
                "restrict_pushes": True
            },
            "develop": {
                "required_reviews": 1,
                "dismiss_stale_reviews": True,
                "required_status_checks": [
                    "validate"
                ],
                "enforce_admins": False
            }
        }
    
    @staticmethod
    def generate_codeowners() -> str:
        """Generate CODEOWNERS file."""
        return """# CODEOWNERS - Auto-assign reviewers

# Default: Data Engineering team
* @org/data-engineering

# Infrastructure changes require platform team
databricks.yml @org/platform-engineering
resources/ @org/platform-engineering
.github/ @org/platform-engineering

# Domain-specific ownership
src/lending/ @org/lending-team
src/risk/ @org/risk-team
src/compliance/ @org/compliance-team

# Security-sensitive changes
**/governance/ @org/data-governance @org/security
**/mnpi/ @org/compliance-team @org/legal
"""
